### ISSUE TITLE
Address search requires lowercase

### ISSUE THREAD

**Issue by jaycle** [tobinbradley/Mecklenburg-County-GeoPortal#3]
When searching for an address, using a capital letter seems to break search. For example, if you were searching for "1800 S Tryon" and spelled it as such, the search results pause after 1800. search works just fine when inputting "1800 s tryon" however.

**Comment by tobinbradley** [comment]
It was actually our corporate firewall eating camel case stuff for some reason. Yay security! I have GeoPortal lower case everything before it sends it now, which fixes the problem while I try to sort out our firewall issues.

Thanks for the catch!
